### ISSUE TITLE
HDOP value in cm?

### ISSUE THREAD

**Issue by jainakshay91** [mavlink/c_library_v1#8]
Is the returned HDOP value in cm? From what I have read about HDOP and how it is calculated, it is just a factor and is a unitless quantity. One needs to multiply the user equivalent range error (UERE) values with the DOP values to obtain a precise range error value. 

Can somebody kindly clarify on this point. 

Thanks, 
Akshay jain

**Comment by LorenzMeier** [comment]
Sorry for not seeing this earlier - this repo is auto-generated and the right place would be the mavlink repo to report. This has been addressed since.
